apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nest-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nest-study
  template:
    metadata:
      labels:
        app: api-nest-study
    spec:
      containers:
        - name: app
          image: paulohsv/api-nest-study:1.2
          ports:
            - containerPort: 3000
